# Site settings
title: DARSHIT RAVANI
twitter_username: 
name: Darshit Ravani

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Instagram
   url: http://instagram.com/d_ravani
 - title: Facebook
   url: http://facebook.com/darshit.ravani.1
 - title: LinkedIn
   url: https://www.linkedin.com/in/darshit-ravani/

#Any buzzword skills you want to include
skills:
 - Finance

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://udayom.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Group Audit Analyst
   start: 2023
   end: Ongoing
   employer: Emirates Group, Dubai, UAE
   description: Working in Group Internal Audit functions - The Third Line of Defence - Cybersecurity Assessment and verifications - Report HH
 - title: Cyber Security Manager
   start: 2022
   end: 2023
   employer: Emirates Flight Catering, Dubai, UAE
   description: Working on Cybersecurity functions including GRC to secure an organisation and keep the operations smooth from a Security perspective.

#Education is required
education:
 - level: Master of Engineering (M.Engg)
   date: 2014
   subject: Information Technology, Mumbai, India
   school: University of Mumbai
 - level: Bachelor of Engineering (B.Engg)
   date: 2012
   subject: Electronics and Telecommunications, Mumbai, India
   school: University of Mumbai

#This section is optional (as is the image link below)
certifications:
   profileurl: https://www.linkedin.com/in/darshit-ravani/
   course:
    - title: OneTrust GRC Professional
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/grc-prof.png
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/OneTrust.png
      date: Nov 06, 2022

about:
   profileurl: https://www.linkedin.com/in/darshit-ravani/

intro: |
   Hello, My name is Darshit J Ravani. Professionally, I have significant experience working <b>across a range of Cyber Security</b> activities, including a strong background of <b>Risk assessment</b> for projects, third party, applications to compliance for the organisation. I have a good grasp of the frameworks such as <b>ISO 27001, PCI-DSS</b> and had multiple opportunities to get the organisations certified by handling end to end activities involved in the process.</br></br>
   Personally, I enjoy working on shell scripts for Automation and Forensically Investigating Cyber Security Incidents to uncover the real <b>intent</b> of an attack/Hack. I like the Automation approach wherever it is possible to implement and promote the DevSecOps culture whenever I get an opportunity to do so. </br></br> <b>Dedicating my</b> efforts towards literature to understand the <b>root cause of Cyber Security events and Hackers perspective/behaviour</b> is a passion of mine.  <b>I also hold myself to a high standard when it comes listening to a problem statement and working to deliver the right solution/practice for my clients</b>.</br></br> 
   I have worked on my <a href="https://www.github.com/udayom" target="_blank">GitHub Profile</a> to provide an overview of my <b>career history and expertise</b> here. You can also find more information here on my <a href="https://www.linkedin.com/in/udayom/" taget="_blank">LinkedIn Profile</a>

#An additional info free-text section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Technical Youtube Tutorials and blog posts that can be checked (pardon my spooky voice-over) 🧑🏻‍💻 - </br></br> 
   <iframe width="560" height="315" src="https://www.youtube.com/embed/9T30_rCWnww" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> </br></br>
   </br>
   <a href="https://www.facebook.com/" taget="_blank">My Facebook </a></br>
   <a href="https://www.instagram.com/" taget="_blank">My Instagram </a></br>
   <a href="https://github.com/darshitjr/darshitjr.github.io/blob/master/img/darshit.pdf" taget="_blank">My CV </a></br>


#A Smarkskill section to add something extra - added personally by OM out of interest and learning - can be text or HTML
smartskill: |
    Hello I am Darshit, I am superman
