# Site settings
title: UDAY KUMAR
twitter_username: udayom
name: Uday Kumar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://udayom.blogspot.com/
 - title: GitHub
   url: https://github.com/udayom/
 - title: Facebook
   url: http://facebook.com/udayom/
 - title: LinkedIn
   url: https://www.linkedin.com/in/udayom/

#Any buzzword skills you want to include
skills:
 - Cyber Security
 - Automation
 - DevOps
 - DevSecOps
 - Digital Forensics
 - Cyber Forensics
 - Ethical Hacking
 - Vulnerability Assessment
 - Penetration Testing
 - Governance
 - Risk Managment
 - Compliance
 - Security Awareness
 - Agile Methodology
 - Training

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://udayom.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Cyber Security Manager
   start: 2018
   end: Ongoing
   employer: Khidmaty Government Services
   description: Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: IT Security Manager
   start: 2017
   end: 2018
   employer: Finacus Solutions
   description: Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: Cyber Security Analyst
   start: 2014
   end: 2017
   employer: Capgemini
   description: Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: Intern Engineer
   start: 2013
   end: 2014
   employer: Asian Associates
   description: Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>

#Education is required
education:
 - level: Master of Engineering (M.Engg)
   date: 2014
   subject: Information Technology
   school: University of Mumbai
 - level: Bachelor of Engineering (B.Engg)
   date: 2012
   subject: Electronics and Telecommunications
   school: University of Mumbai

#This section is optional (as is the image link below)
certifications:
   profileurl: https://www.linkedin.com/in/udayom
   course:
    - title: Certified Ethical Hacking
      link: https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/
      optionalimage: https://udemy-images.udemy.com/course/240x135/157842_9d33_8.jpg
      date: February 4, 2019
    - title: Diploma in Cyber Law
      link: https://www.asianlaws.org
      optionalimage: https://www.asianlaws.org/img2019/slider_dcl.jpg
      date: January 28, 2018
    - title: ISO 27001 Lead Auditor
      link: https://www.tuv-sud.in/in-en/activity/auditing-system-certification/iso-27001-information-security-management-system
      date: February 4, 2017
    - title: Agile Methodology & Project Management
      link: https://www.udemy.com/agile-crash-course
      optionalimage: https://udemy-images.udemy.com/course/240x135/864146_dbd7_10.jpg
      date: January 28, 2018

#List of interesting Github repo/projects to include - optional
github:
 - udayom/udayom.github.io
 - udayom/OSCP-Study-Notes
 - udayom/Capistrano-Deploy
 - udayom/glpi
 - udayom/PyPractice

#Stackoverflow flair is optional
hackthebox:
   profileurl: https://www.hackthebox.eu/home/users/profile/74322
   flairimageurl: https://www.hackthebox.eu/storage/avatars/fcb23cd55da58c4e1f115bf2eb48e6a8.png

intro: |
  With 6+ years of Experience, I have Majorly worked on Cyber Security activities and Automation of the Industry based process/Technology.  <br/><br/>
  I enjoy working on shell scripts for Automation and Forensically Investigating the Cyber Security Incidents to find out the real purpose of the attack/Hack. <br/><br/>
  I have always dedicated more efforts to literature survey where amount of time to understand the issue seemed quite a lot. Listening is very important and I listen very well. I have worked on my  <a href="https://www.github.com/udayom" target="_blank">GitHub Profile</a> to present it in Resume format.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Get More information here on <a href="https://www.linkedin.com/in/udayom/" taget="_blank">LinkedIn Profile</a>
