# Site settings
title: UDAY KUMAR
twitter_username: udayom0
name: Uday Kumar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://udayom.blogspot.com/
 - title: GitHub
   url: https://github.com/udayom/
 - title: Facebook
   url: http://facebook.com/udayom/
 - title: LinkedIn
   url: https://www.linkedin.com/in/udayom/

#Any buzzword skills you want to include
skills:
 - Cyber Security
 - Automation
 - DevOps
 - DevSecOps
 - Digital Forensics
 - Cyber Forensics
 - Ethical Hacking
 - Vulnerability Assessment
 - Penetration Testing
 - Governance
 - Risk Managment
 - Compliance
 - Security Awareness
 - Agile Methodology
 - Training

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://udayom.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Cyber Security Lead
   start: 2018
   end: Ongoing
   employer: Khidmaty Government Services
   description: Operational and Governance related tasks that relates to Security for Client ASGC, Dubai. Major task includes the Defining and Implementation of Information Security Policies and Procedures as per ISO27001 Standards. The Automation of Management Reports, Analyze the vulnerabilities found in infrastructure by Vulnerability Analysis and Penetration Testing (Manual+Automated), Threat Remediation, highlight risk to management, risk assessment, vendor management, security checks for vendor, hardening checks on the Oracle Linux operating system, schedule Antivirus scans and highlight the Major vulnerability to IT Infra team, schedule patch management, Ensure compliance of the policies on the servers, Manage and Administer IT security and Forensic tools such as LanSweeper, QualysGuard, Symantec Endpoint protection, ATP, ETP, EDR, MS Office 365 Admin, Azure Portal Admin, Cloud Server Management Activities like New Provisioning server, Migrate, Destroy server etc. Perform VAPT on in-house Applications using OpenVAS. SIEM configuration (AlienVault), Cyber Operations, Reporting, Demonstration. Investigation of the attacks, Fortinet Firewall Rules review (nipper), log and memory based analysis, Forensic evidence finding (SIEM Log and Dump based) Technical Policy defining and Implementation in Symantec Endpoint Protection, Data Leakage Protection (DLP), Email+Cloud Security, Email Threat Protection (FireEye, Microsoft, Mimecast), Web Isolation modules. Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: CISO (IT Security Manager)
   start: 2017
   end: 2018
   employer: Finacus Solutions
   description: Automation with Security Compliance checks, Policy procedures defining, ISO/IEC 27001, PCI-DSS implementation, Process Management, Incident Management, Change management, Automation of operational tasks, Internal Security Auditing, VAPT, Continuous Development and Automation with open-source tools (DevOps), Complete Financial Domain, Payment gateway interface Audit as per PCI DSS Compliance, Process Auditing. Reporting ROC (Report on Compliance), ROV (Report on Validation), Performing ASV Scans as part of PCI DSS Implementation. Major Responsibility included all the Operational and Governance related tasks that relates to Security for Finacus Solutions Pvt. Ltd. which deals with its various clients (100+) as Reputed Banks spread across India. Major task included the Defining and Implementation of Information Security Policies and Procedures. The Automation of business requirements and management, so far covered Change management, Incident Management, Asset Inventory, Helpdesk, Ticketing, Effort Tracking and Documentation storage Automation.  Administering Azure account for system integration of ticketing system. From DevSecOps section, have covered configuration, implementation and Maintenance of various monitoring tool such as Nagios, Baretail, OpenNMS, Graylog, RanCID. Automated Email/SMS Triggering from monitoring tool if critical alert arrives as per business requirement. Configuring and Administration of Manage Engine PIM Tool Password Manager Pro, WatchGuard Firewall Rules, Implementing Trend Micro Anti-Virus, Involvement of banking domain requires more emphasize on PCI-DSS compliance which talks about internal and external Auditing reports. Jenkins Automation for day to day jobs as well as code deployment on Linux servers via Shell Scripts developed and implemented. Following Agile Way of Methodology with Sprint Framework and DevSecOps Practice to achieve Automation with End to End Project workflow Integration including Automated Security Check Components! Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: Cyber Security Analyst
   start: 2014
   end: 2017
   employer: Capgemini
   description:  Governance Security - Manage Audits, Compliance check along with certifications for various standards such as ISO 27001- 2013 and PCI DSS. Multi-operational experience in Networking Operations, Systems Administration, Security and Audit & Support of Heterogeneous IT Infrastructure and BCP/DR. Handling Incident Management.Formulating, Reviewing, Upgrading, Developing Policy, Procedures and Guidelines for elements governing/connected to ISO Standards, Analyze SIEM tools, IDS and auctioning on alerts Operational Security- Involved in Vulnerability Analysis and Penetration Testing, worked on tools like burpsuite, IBM Appscanner, OWASP top 10, wapiti, Paros proxy, Nikto, Nessus, metasploite etc.IPS and DDOS mitigation device reports analysis firewall rule dump and analysis, proxy logs, user administration, OSSEC, SIEM tool monitoring and configuration, ITIL Tool - Service now.Cyber Forensics and Analysis using tools like The Sleuth Kit, Autopsy, Rekall, DumpIT, Volatility, log2timeline and most of the tools from Kali Linux OS. Handled SOC activities in which Analysis of complete trail of activities of user based on the logs and extracting footprints for legal purpose to be dealt with Cyber Law team. DevSecOps- Digital Transformation of Project-  Worked on Multiple open source tools like Nagios, Munin, graphite, Jenkins, Apache,  ldap, mongodb, maven, Exim, ELK stack, graylog, graphite, redis-cache, memcache, exim, Linux shell scripting, Automation with Jenkins, Ansible, PuppetTo design business rule-based dashboards in AppDynamic. To make dashboards and alerts in AppDynamics based on Business requirement. AppDynamics deployment and complete setup Project Management- Experience on Atlassian tools like JIRA, Confluence, stash, bitbucket. Studied ITIL Fv4 & worked on Kanban boards for project progress tracking. Project management experience for deployment, schedule.Good at Incident, Change management, onshore & offshore interaction & Documentation. Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: SOC Intern Engineer
   start: 2013
   end: 2014
   employer: Asian Associates
   description: Performed Vulnerability Analysis and Penetration Testing, worked on Linux based open source tools like burpsuite, OWASP, Nikto, wapiti, Paros proxy, Nessus, metasploite etc. Implemented and Administered IPS and Performed DDOS mitigation device reports analysis, Forensic Analysis on attack trace, proxy logs, user administration. Complete SOC level Monitoring setup including Nagios, OSSEC, SIEM tool monitoring and configuration. Tweaking in existing scripts/IT Tools for performance boosting and Automating of the tasks performed. Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>

#Education is required
education:
 - level: Master of Engineering (M.Engg)
   date: 2014
   subject: Information Technology
   school: University of Mumbai
 - level: Bachelor of Engineering (B.Engg)
   date: 2012
   subject: Electronics and Telecommunications
   school: University of Mumbai

#This section is optional (as is the image link below)
certifications:
   profileurl: https://www.linkedin.com/in/udayom
   course:
    - title: Certified Chief Information Security Officer (C|CISO)
      link: https://ciso.eccouncil.org/cciso-certification/
      optionalimage: https://mydigitalcollege.com/wp-content/uploads/2018/12/ceh-cciso.png
      date: April 10, 2019
    - title: AWS Certified Solution Architect - Associate
      link: https://aws.amazon.com/certification/certified-solutions-architect-associate/
      optionalimage: https://udemy-images.udemy.com/course/240x135/362328_91f3_10.jpg
      date: March 02, 2019
    - title: AWS Certified Cloud Practitioner
      link: https://aws.amazon.com/certification/certified-cloud-practitioner/
      optionalimage: https://udemy-images.udemy.com/course/240x135/1360446_f69e.jpg
      date: February 23, 2019
    - title: Certified Ethical Hacking
      link: https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/
      optionalimage: https://crushtheinfosecexams.com/wp-content/uploads/2017/05/Certified-Ethical-Hacking.jpg
      date: February 4, 2019
    - title: Diploma in Cyber Law
      link: https://www.asianlaws.org
      optionalimage: https://udemy-images.udemy.com/course/240x135/1305460_486d_2.jpg
      date: January 28, 2018
    - title: ISO 27001 Lead Auditor
      link: https://www.tuv-sud.in/in-en/activity/auditing-system-certification/iso-27001-information-security-management-system
      optionalimage: http://ravikirankunder.com/wp-content/uploads/2016/11/ISO27k.png
      date: February 4, 2017
    - title: Agile Methodology & Project Management
      link: https://www.udemy.com/agile-crash-course
      optionalimage: https://udemy-images.udemy.com/course/240x135/864146_dbd7_10.jpg
      date: January 28, 2018

#List of interesting Github repo/projects to include - optional
github:
 - udayom/udayom.github.io
 - udayom/OSCP-Study-Notes
 - udayom/Capistrano-Deploy
 - udayom/glpi
 - udayom/PyPractice

#Stackoverflow flair is optional
hackthebox:
   profileurl: https://www.hackthebox.eu/home/users/profile/74322
   flairimageurl: https://www.hackthebox.eu/storage/avatars/fcb23cd55da58c4e1f115bf2eb48e6a8.png

about:
   profileurl: https://www.linkedin.com/in/udayom/

intro: |
  With 7+ years of Experience, I have Majorly worked on Cyber Security activities and Automation of the Industry based process/Technology.  <br/><br/>
  I enjoy working on shell scripts for Automation and Forensically Investigating the Cyber Security Incidents to find out the real purpose of the attack/Hack. <br/><br/>
  I have always dedicated more efforts to literature survey where amount of time to understand the issue seemed quite a lot. Listening is very important and I listen very well. I have worked on my  <a href="https://www.github.com/udayom" target="_blank">GitHub Profile</a> to present it in Resume format.    Get More information here on <a href="https://www.linkedin.com/in/udayom/" taget="_blank">LinkedIn Profile</a> 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Few Youtube Tutorials and blog posts you can take a look at - 
   <iframe width="560" height="315" src="https://www.youtube.com/embed/9T30_rCWnww" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
