# Site settings
title: Uday Kumar
twitter_username: udayom
name: Uday Kumar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://udayom.blogspot.com/
 - title: GitHub
   url: https://github.com/udayom
 - title: Facebook
   url: http://facebook.com/udayom
 - title: LinkedIn
   url: https://www.linkedin.com/in/udayom

#Any buzzword skills you want to include
skills:
 - Cyber Security
 - Automation
 - DevOps
 - DevSecOps
 - Digital Forensics
 - Cyber Forensics
 - Ethical Hacking
 - Vulnerability Assessment
 - Penetration Testing
 - Governance
 - Risk Managment
 - Compliance
 - Security Awareness
 - Training
 - Agile Methology
 - Technical Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://udayom.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Cyber Security Manager
   start: 2018
   end: Ongoing
   employer: Khidmaty Government Services
   description: Check More on <a href="https://www.linkedin.com/udayom/in" taget="_blank">LinkedIn Profile</a>.
 - title: IT Security Manager
   start: 2017
   end: 2018
   employer: Finacus Solutions
   description: Check More on <a href="https://www.linkedin.com/udayom/in" taget="_blank">LinkedIn Profile</a>.
 - title: Cyber Security Analyst
   start: 2014
   end: 2017
   employer: Capgemini
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: SOC Engineer 
   start: 2013
   end: 2014
   employer: Asian Associates
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Master of Engineering (M.Engg)
   date: 2014
   subject: Information Technology
   school: University of Mumbai
 - level: Bachelor of Engineering (B.Engg)
   date: 2012
   subject: Electronics and Telecommunications
   school: University of Mumbai

#This section is optional (as is the image link below)
Certifications:
   profileurl: https://www.linkedin.com/in/udayom
   courses:
    - title: Certified Ethical Hacking
      link: https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/
      optionalimage: https://udemy-images.udemy.com/course/240x135/157842_9d33_8.jpg
      date: February 4, 2019
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - udayom/udayom.github.io
 - udayom/ScaLambda
 - udayom/opinionated-akka-http
 - udayom/food2vec
 - udayom/microservices
 - udayom/spring-social-geeklist
 - udayom/spring-social-stackoverflow
 - udayom/genotype
 - udayom/footweets
 - udayom/ElasticSearchGradle

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/258813/rhinds
   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am an engineer with 15 years experience working in technology. I have primarily worked on the JVM, but have worked across a broad range of technologies thereon: Java, Groovy, Android, Coldfusion and most recently Scala. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages on the JVM, I recognise that good code is contextual).<br/><br/>
  I have worked in large scale consultancy roles across Europe as well as a mix of startup experience (including one that was acquired) and I am currently the Chief Technology Officer at a legal-tech startup called <a href="https://www.basementcrowd.com" target="_blank">Basement Crowd</a> where we are building innovative products to serve the legal industry.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Get More information here on <a href="https://www.linkedin.com/udayom/in" taget="_blank">LinkedIn Profile</a>
